import csv
import os
import time
import numpy as np
import mxnet as mx
from bert_embedding import BertEmbedding

ctx = mx.gpu(0)
bert = BertEmbedding(ctx=ctx, max_seq_length=768, batch_size=8)


start_time = time.time()

project_path = 'GraphRank/'
dataset = 'Nguyen2007'
doc_path = project_path + 'data/processed_' + dataset +'/filtered_graph_edges_stemmed/'

files = os.listdir(doc_path)

files = files[:]


save_path = project_path + 'data/processed_' + dataset +'/doc_emb/'
if not os.path.exists(save_path):
    os.makedirs(save_path)

avg_len = 0
for n, file in enumerate(files):

    candidates = []

    with open(doc_path + file, newline='') as csvfile:
        spamreader = csv.reader(csvfile, delimiter=',')

        for row in spamreader:
            k = row[0][2:-2].split("', '")
            node1, node2 = k[0], k[1]

            # node1, node2 = node1[:node1.find('_')], node2[:node2.find('_')]
            # this will delete the last digit, we do not use _ any more

            # print(node1, node2)

            for node in [node1, node2]:
                if node in candidates:
                    continue
                else:
                    candidates.append(node)

    avg_len += len(candidates)

    candidates = ' '.join(candidates)
    """(0401) here is important, we integrate all candi into one sentence.
    so we can say, the topic emb is generated by using attn"""

    node_emb = bert([candidates])
    nodes = node_emb[0][0]
    embs = node_emb[0][1]

    w2 = csv.writer(open(save_path + file.replace('edges.csv', 'emb.csv'), "a"))
    for i, k in enumerate(nodes):
        # print(k, embs[i])
        w2.writerow([k, embs[i]])

    crt_time = time.time()
    print(n + 1, "th file", file, "running time", crt_time - start_time)


print(avg_len/len(files))  # 111

